// Dummy data shared across prototype pages — replace with real backend data

const lexiconWords = [
  { word: '走る', reading: 'はしる', meaning: 'to run', type: 'godan-verb', exampleJp: '公園を走る。', exampleEn: 'I run in the park.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-03-22' },
  { word: '美しい', reading: 'うつくしい', meaning: 'beautiful', type: 'i-adjective', exampleJp: '美しい花が咲いている。', exampleEn: 'Beautiful flowers are blooming.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: null },
  { word: '話す', reading: 'はなす', meaning: 'to speak; to talk', type: 'godan-verb', exampleJp: '日本語を話す。', exampleEn: 'I speak Japanese.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: '2026-03-10' },
  { word: '静か', reading: 'しずか', meaning: 'quiet', type: 'na-adjective', exampleJp: '図書館は静かだ。', exampleEn: 'The library is quiet.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-03-20' },
  { word: '始める', reading: 'はじめる', meaning: 'to begin; to start', type: 'ichidan-verb', exampleJp: '仕事を始める。', exampleEn: 'I start work.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: null },
  { word: '天気', reading: 'てんき', meaning: 'weather', type: 'noun', exampleJp: '今日は天気がいい。', exampleEn: 'The weather is nice today.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-02-15' },
  { word: '忘れる', reading: 'わすれる', meaning: 'to forget', type: 'ichidan-verb', exampleJp: '名前を忘れる。', exampleEn: 'I forget the name.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: '2026-03-23' },
  { word: '危ない', reading: 'あぶない', meaning: 'dangerous', type: 'i-adjective', exampleJp: 'この道は危ない。', exampleEn: 'This road is dangerous.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: null },
  { word: '選ぶ', reading: 'えらぶ', meaning: 'to choose; to select', type: 'godan-verb', exampleJp: '好きな色を選ぶ。', exampleEn: 'I choose my favorite color.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-01-08' },
  { word: '問題', reading: 'もんだい', meaning: 'problem; question', type: 'noun', exampleJp: '問題を解く。', exampleEn: 'I solve the problem.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: '2026-03-18' },
  { word: '暖かい', reading: 'あたたかい', meaning: 'warm', type: 'i-adjective', exampleJp: '今日は暖かい。', exampleEn: 'It is warm today.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-03-22' },
  { word: '借りる', reading: 'かりる', meaning: 'to borrow', type: 'ichidan-verb', exampleJp: '本を借りる。', exampleEn: 'I borrow a book.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: null },
  { word: '経験', reading: 'けいけん', meaning: 'experience', type: 'noun', exampleJp: 'いい経験になった。', exampleEn: 'It became a good experience.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: '2026-03-10' },
  { word: '集める', reading: 'あつめる', meaning: 'to collect; to gather', type: 'ichidan-verb', exampleJp: '切手を集める。', exampleEn: 'I collect stamps.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-03-20' },
  { word: '複雑', reading: 'ふくざつ', meaning: 'complicated; complex', type: 'na-adjective', exampleJp: 'この地図は複雑だ。', exampleEn: 'This map is complicated.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: null },
  { word: '届く', reading: 'とどく', meaning: 'to arrive; to reach', type: 'godan-verb', exampleJp: '手紙が届く。', exampleEn: 'The letter arrives.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-02-15' },
  { word: '練習', reading: 'れんしゅう', meaning: 'practice', type: 'noun', exampleJp: '毎日練習する。', exampleEn: 'I practice every day.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: '2026-03-23' },
  { word: '眠い', reading: 'ねむい', meaning: 'sleepy', type: 'i-adjective', exampleJp: 'とても眠い。', exampleEn: 'I am very sleepy.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: null },
  { word: '伝える', reading: 'つたえる', meaning: 'to convey; to tell', type: 'ichidan-verb', exampleJp: '気持ちを伝える。', exampleEn: 'I convey my feelings.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-01-08' },
  { word: '丁寧', reading: 'ていねい', meaning: 'polite; careful', type: 'na-adjective', exampleJp: '丁寧に説明する。', exampleEn: 'I explain politely.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: '2026-03-18' },
  { word: '探す', reading: 'さがす', meaning: 'to search; to look for', type: 'godan-verb', exampleJp: '鍵を探す。', exampleEn: 'I look for the key.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-03-22' },
  { word: '景色', reading: 'けしき', meaning: 'scenery; view', type: 'noun', exampleJp: '景色がきれいだ。', exampleEn: 'The scenery is beautiful.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: null },
  { word: '壊れる', reading: 'こわれる', meaning: 'to break (intransitive)', type: 'ichidan-verb', exampleJp: '時計が壊れる。', exampleEn: 'The clock breaks.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: '2026-03-10' },
  { word: '残念', reading: 'ざんねん', meaning: 'regrettable; unfortunate', type: 'na-adjective', exampleJp: '残念な結果だった。', exampleEn: 'It was an unfortunate result.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-03-20' },
  { word: '誘う', reading: 'さそう', meaning: 'to invite', type: 'godan-verb', exampleJp: '友達を誘う。', exampleEn: 'I invite a friend.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: null },
  { word: '約束', reading: 'やくそく', meaning: 'promise; appointment', type: 'noun', exampleJp: '約束を守る。', exampleEn: 'I keep the promise.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-02-15' },
  { word: '優しい', reading: 'やさしい', meaning: 'kind; gentle', type: 'i-adjective', exampleJp: '彼は優しい人だ。', exampleEn: 'He is a kind person.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: '2026-03-23' },
  { word: '受ける', reading: 'うける', meaning: 'to receive; to take (exam)', type: 'ichidan-verb', exampleJp: '試験を受ける。', exampleEn: 'I take an exam.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: null },
  { word: '自由', reading: 'じゆう', meaning: 'freedom; free', type: 'na-adjective', exampleJp: '自由な時間が欲しい。', exampleEn: 'I want free time.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-01-08' },
  { word: '捨てる', reading: 'すてる', meaning: 'to throw away', type: 'ichidan-verb', exampleJp: 'ゴミを捨てる。', exampleEn: 'I throw away the trash.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: '2026-03-18' },
  { word: '泳ぐ', reading: 'およぐ', meaning: 'to swim', type: 'godan-verb', exampleJp: '海で泳ぐ。', exampleEn: 'I swim in the sea.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-03-22' },
  { word: '運ぶ', reading: 'はこぶ', meaning: 'to carry', type: 'godan-verb', exampleJp: '荷物を運ぶ。', exampleEn: 'I carry the luggage.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: null },
  { word: '起きる', reading: 'おきる', meaning: 'to wake up; to get up', type: 'ichidan-verb', exampleJp: '早く起きる。', exampleEn: 'I wake up early.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: '2026-03-10' },
  { word: '落ちる', reading: 'おちる', meaning: 'to fall', type: 'ichidan-verb', exampleJp: '葉が落ちる。', exampleEn: 'The leaves fall.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-03-20' },
  { word: '変える', reading: 'かえる', meaning: 'to change', type: 'ichidan-verb', exampleJp: '計画を変える。', exampleEn: 'I change the plan.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: null },
  { word: '考える', reading: 'かんがえる', meaning: 'to think; to consider', type: 'ichidan-verb', exampleJp: '答えを考える。', exampleEn: 'I think of the answer.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-02-15' },
  { word: '決める', reading: 'きめる', meaning: 'to decide', type: 'ichidan-verb', exampleJp: '目標を決める。', exampleEn: 'I decide on a goal.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: '2026-03-23' },
  { word: '聞こえる', reading: 'きこえる', meaning: 'to be audible; to hear', type: 'ichidan-verb', exampleJp: '音楽が聞こえる。', exampleEn: 'I can hear the music.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: null },
  { word: '比べる', reading: 'くらべる', meaning: 'to compare', type: 'ichidan-verb', exampleJp: '値段を比べる。', exampleEn: 'I compare the prices.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-01-08' },
  { word: '困る', reading: 'こまる', meaning: 'to be troubled; to be in a fix', type: 'godan-verb', exampleJp: '道に迷って困る。', exampleEn: 'I am troubled after getting lost.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: '2026-03-18' },
  { word: '転ぶ', reading: 'ころぶ', meaning: 'to fall down; to tumble', type: 'godan-verb', exampleJp: '滑って転ぶ。', exampleEn: 'I slip and fall down.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-03-22' },
  { word: '触る', reading: 'さわる', meaning: 'to touch', type: 'godan-verb', exampleJp: '猫に触る。', exampleEn: 'I touch the cat.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: null },
  { word: '調べる', reading: 'しらべる', meaning: 'to investigate; to look up', type: 'ichidan-verb', exampleJp: '言葉を調べる。', exampleEn: 'I look up the word.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: '2026-03-10' },
  { word: '信じる', reading: 'しんじる', meaning: 'to believe', type: 'ichidan-verb', exampleJp: '友達を信じる。', exampleEn: 'I believe my friend.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-03-20' },
  { word: '育てる', reading: 'そだてる', meaning: 'to raise; to bring up', type: 'ichidan-verb', exampleJp: '子供を育てる。', exampleEn: 'I raise a child.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: null },
  { word: '続ける', reading: 'つづける', meaning: 'to continue', type: 'ichidan-verb', exampleJp: '練習を続ける。', exampleEn: 'I continue practicing.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-02-15' },
  { word: '手伝う', reading: 'てつだう', meaning: 'to help; to assist', type: 'godan-verb', exampleJp: '母を手伝う。', exampleEn: 'I help my mother.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: '2026-03-23' },
  { word: '直す', reading: 'なおす', meaning: 'to fix; to correct', type: 'godan-verb', exampleJp: '時計を直す。', exampleEn: 'I fix the clock.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: null },
  { word: '並ぶ', reading: 'ならぶ', meaning: 'to line up; to stand in a row', type: 'godan-verb', exampleJp: '列に並ぶ。', exampleEn: 'I line up in the queue.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-01-08' },
  { word: '逃げる', reading: 'にげる', meaning: 'to run away; to escape', type: 'ichidan-verb', exampleJp: '危険から逃げる。', exampleEn: 'I escape from danger.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: '2026-03-18' },
  { word: '脱ぐ', reading: 'ぬぐ', meaning: 'to take off (clothes)', type: 'godan-verb', exampleJp: '靴を脱ぐ。', exampleEn: 'I take off my shoes.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-03-22' },
  { word: '登る', reading: 'のぼる', meaning: 'to climb', type: 'godan-verb', exampleJp: '山に登る。', exampleEn: 'I climb the mountain.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: null },
  { word: '払う', reading: 'はらう', meaning: 'to pay', type: 'godan-verb', exampleJp: '料金を払う。', exampleEn: 'I pay the fee.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: '2026-03-10' },
  { word: '減る', reading: 'へる', meaning: 'to decrease; to diminish', type: 'godan-verb', exampleJp: '体重が減る。', exampleEn: 'My weight decreases.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-03-20' },
  { word: '曲がる', reading: 'まがる', meaning: 'to turn; to bend', type: 'godan-verb', exampleJp: '角を曲がる。', exampleEn: 'I turn the corner.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: null },
  { word: '守る', reading: 'まもる', meaning: 'to protect; to keep (a promise)', type: 'godan-verb', exampleJp: 'ルールを守る。', exampleEn: 'I follow the rules.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-02-15' },
  { word: '見える', reading: 'みえる', meaning: 'to be visible; can see', type: 'ichidan-verb', exampleJp: '海が見える。', exampleEn: 'I can see the sea.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: '2026-03-23' },
  { word: '向かう', reading: 'むかう', meaning: 'to head toward; to face', type: 'godan-verb', exampleJp: '駅に向かう。', exampleEn: 'I head toward the station.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: null },
  { word: '戻る', reading: 'もどる', meaning: 'to return; to go back', type: 'godan-verb', exampleJp: '家に戻る。', exampleEn: 'I return home.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-01-08' },
  { word: '焼く', reading: 'やく', meaning: 'to bake; to grill', type: 'godan-verb', exampleJp: 'パンを焼く。', exampleEn: 'I bake bread.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: '2026-03-18' },
  { word: '意見', reading: 'いけん', meaning: 'opinion', type: 'noun', exampleJp: '意見を言う。', exampleEn: 'I state my opinion.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-03-22' },
  { word: '機会', reading: 'きかい', meaning: 'opportunity; chance', type: 'noun', exampleJp: '機会を活かす。', exampleEn: 'I make use of the opportunity.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: null },
  { word: '記念', reading: 'きねん', meaning: 'commemoration; memory', type: 'noun', exampleJp: '記念写真を撮る。', exampleEn: 'I take a commemorative photo.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: '2026-03-10' },
  { word: '計画', reading: 'けいかく', meaning: 'plan', type: 'noun', exampleJp: '計画を立てる。', exampleEn: 'I make a plan.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-03-20' },
  { word: '原因', reading: 'げんいん', meaning: 'cause; reason', type: 'noun', exampleJp: '事故の原因を調べる。', exampleEn: 'I investigate the cause of the accident.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: null },
  { word: '事故', reading: 'じこ', meaning: 'accident', type: 'noun', exampleJp: '交通事故が起きた。', exampleEn: 'A traffic accident occurred.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-02-15' },
  { word: '準備', reading: 'じゅんび', meaning: 'preparation', type: 'noun', exampleJp: '準備ができた。', exampleEn: 'The preparations are done.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: '2026-03-23' },
  { word: '場所', reading: 'ばしょ', meaning: 'place; location', type: 'noun', exampleJp: '待ち合わせの場所を決める。', exampleEn: 'I decide on a meeting place.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: null },
  { word: '心配', reading: 'しんぱい', meaning: 'worry; concern', type: 'noun', exampleJp: '心配をかけてごめん。', exampleEn: 'Sorry for causing worry.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-01-08' },
  { word: '生活', reading: 'せいかつ', meaning: 'daily life; living', type: 'noun', exampleJp: '生活が豊かになった。', exampleEn: 'My life became rich.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: '2026-03-18' },
  { word: '説明', reading: 'せつめい', meaning: 'explanation', type: 'noun', exampleJp: '説明を聞く。', exampleEn: 'I listen to the explanation.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-03-22' },
  { word: '相談', reading: 'そうだん', meaning: 'consultation; discussion', type: 'noun', exampleJp: '先生に相談する。', exampleEn: 'I consult with the teacher.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: null },
  { word: '注意', reading: 'ちゅうい', meaning: 'caution; attention', type: 'noun', exampleJp: '注意して運転する。', exampleEn: 'I drive carefully.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: '2026-03-10' },
  { word: '日常', reading: 'にちじょう', meaning: 'everyday; daily life', type: 'noun', exampleJp: '日常の生活を大切にする。', exampleEn: 'I value everyday life.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-03-20' },
  { word: '費用', reading: 'ひよう', meaning: 'cost; expense', type: 'noun', exampleJp: '費用を計算する。', exampleEn: 'I calculate the cost.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: null },
  { word: '文化', reading: 'ぶんか', meaning: 'culture', type: 'noun', exampleJp: '日本の文化を学ぶ。', exampleEn: 'I learn about Japanese culture.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-02-15' },
  { word: '方法', reading: 'ほうほう', meaning: 'method; way', type: 'noun', exampleJp: '勉強の方法を変える。', exampleEn: 'I change my study method.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: '2026-03-23' },
  { word: '理由', reading: 'りゆう', meaning: 'reason', type: 'noun', exampleJp: '理由を説明する。', exampleEn: 'I explain the reason.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: null },
  { word: '旅行', reading: 'りょこう', meaning: 'travel; trip', type: 'noun', exampleJp: '旅行の計画を立てる。', exampleEn: 'I make travel plans.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-01-08' },
  { word: '明るい', reading: 'あかるい', meaning: 'bright; cheerful', type: 'i-adjective', exampleJp: '部屋が明るい。', exampleEn: 'The room is bright.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: '2026-03-18' },
  { word: '怪しい', reading: 'あやしい', meaning: 'suspicious; strange', type: 'i-adjective', exampleJp: '怪しい人がいる。', exampleEn: 'There is a suspicious person.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-03-22' },
  { word: '忙しい', reading: 'いそがしい', meaning: 'busy', type: 'i-adjective', exampleJp: '毎日忙しい。', exampleEn: 'I am busy every day.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: null },
  { word: '嬉しい', reading: 'うれしい', meaning: 'happy; glad', type: 'i-adjective', exampleJp: '合格して嬉しい。', exampleEn: 'I am happy to have passed.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: '2026-03-10' },
  { word: '悲しい', reading: 'かなしい', meaning: 'sad', type: 'i-adjective', exampleJp: '別れが悲しい。', exampleEn: 'The farewell is sad.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-03-20' },
  { word: '難しい', reading: 'むずかしい', meaning: 'difficult', type: 'i-adjective', exampleJp: 'この問題は難しい。', exampleEn: 'This problem is difficult.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: null },
  { word: '珍しい', reading: 'めずらしい', meaning: 'rare; unusual', type: 'i-adjective', exampleJp: '珍しい鳥を見た。', exampleEn: 'I saw a rare bird.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-02-15' },
  { word: '厳しい', reading: 'きびしい', meaning: 'strict; severe', type: 'i-adjective', exampleJp: '先生が厳しい。', exampleEn: 'The teacher is strict.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: '2026-03-23' },
  { word: '悔しい', reading: 'くやしい', meaning: 'frustrated; vexed', type: 'i-adjective', exampleJp: '負けて悔しい。', exampleEn: 'I feel frustrated after losing.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: null },
  { word: '正しい', reading: 'ただしい', meaning: 'correct; right', type: 'i-adjective', exampleJp: '正しい答えを選ぶ。', exampleEn: 'I choose the correct answer.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-01-08' },
  { word: '便利', reading: 'べんり', meaning: 'convenient', type: 'na-adjective', exampleJp: 'スマホは便利だ。', exampleEn: 'Smartphones are convenient.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: '2026-03-18' },
  { word: '不便', reading: 'ふべん', meaning: 'inconvenient', type: 'na-adjective', exampleJp: '田舎は不便だ。', exampleEn: 'The countryside is inconvenient.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-03-22' },
  { word: '正確', reading: 'せいかく', meaning: 'accurate; precise', type: 'na-adjective', exampleJp: '正確な情報が必要だ。', exampleEn: 'Accurate information is needed.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: null },
  { word: '大切', reading: 'たいせつ', meaning: 'important; precious', type: 'na-adjective', exampleJp: '時間を大切にする。', exampleEn: 'I value my time.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: '2026-03-10' },
  { word: '必要', reading: 'ひつよう', meaning: 'necessary', type: 'na-adjective', exampleJp: '努力が必要だ。', exampleEn: 'Effort is necessary.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-03-20' },
  { word: '豊か', reading: 'ゆたか', meaning: 'rich; abundant', type: 'na-adjective', exampleJp: '自然が豊かな国だ。', exampleEn: 'It is a country rich in nature.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: null },
  { word: '適切', reading: 'てきせつ', meaning: 'appropriate; suitable', type: 'na-adjective', exampleJp: '適切な言葉を選ぶ。', exampleEn: 'I choose appropriate words.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-23', lastDrilled: '2026-02-15' },
  { word: '十分', reading: 'じゅうぶん', meaning: 'sufficient; enough', type: 'na-adjective', exampleJp: '準備は十分だ。', exampleEn: 'The preparation is sufficient.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-18', lastDrilled: '2026-03-23' },
  { word: '真剣', reading: 'しんけん', meaning: 'serious; earnest', type: 'na-adjective', exampleJp: '真剣に考える。', exampleEn: 'I think seriously.', correct: 0, incorrect: 0, target: 3, createdAt: '2026-03-01', lastDrilled: null },
  { word: '安全', reading: 'あんぜん', meaning: 'safe; secure', type: 'na-adjective', exampleJp: 'この道は安全だ。', exampleEn: 'This road is safe.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-12-01', lastDrilled: '2026-01-08' },
  { word: '特別', reading: 'とくべつ', meaning: 'special', type: 'na-adjective', exampleJp: '今日は特別な日だ。', exampleEn: 'Today is a special day.', correct: 0, incorrect: 0, target: 3, createdAt: '2025-06-01', lastDrilled: '2026-03-18' },
];

const drillWords = [
  { word: '走る', reading: 'はしる', meaning: 'to run', type: 'godan-verb', exampleJp: '公園を走る。', exampleEn: '"I run in the park."' },
  { word: '美しい', reading: 'うつくしい', meaning: 'beautiful', type: 'i-adjective', exampleJp: '美しい花が咲いている。', exampleEn: '"Beautiful flowers are blooming."' },
  { word: '話す', reading: 'はなす', meaning: 'to speak; to talk', type: 'godan-verb', exampleJp: '日本語を話す。', exampleEn: '"I speak Japanese."' },
  { word: '静か', reading: 'しずか', meaning: 'quiet', type: 'na-adjective', exampleJp: '図書館は静かだ。', exampleEn: '"The library is quiet."' },
  { word: '始める', reading: 'はじめる', meaning: 'to begin; to start', type: 'ichidan-verb', exampleJp: '仕事を始める。', exampleEn: '"I start work."' },
  { word: '天気', reading: 'てんき', meaning: 'weather', type: 'noun', exampleJp: '今日は天気がいい。', exampleEn: '"The weather is nice today."' },
  { word: '忘れる', reading: 'わすれる', meaning: 'to forget', type: 'ichidan-verb', exampleJp: '名前を忘れる。', exampleEn: '"I forget the name."' },
  { word: '危ない', reading: 'あぶない', meaning: 'dangerous', type: 'i-adjective', exampleJp: 'この道は危ない。', exampleEn: '"This road is dangerous."' },
  { word: '選ぶ', reading: 'えらぶ', meaning: 'to choose; to select', type: 'godan-verb', exampleJp: '好きな色を選ぶ。', exampleEn: '"I choose my favorite color."' },
  { word: '問題', reading: 'もんだい', meaning: 'problem; question', type: 'noun', exampleJp: '問題を解く。', exampleEn: '"I solve the problem."' },
  { word: '暖かい', reading: 'あたたかい', meaning: 'warm', type: 'i-adjective', exampleJp: '今日は暖かい。', exampleEn: '"It is warm today."' },
  { word: '借りる', reading: 'かりる', meaning: 'to borrow', type: 'ichidan-verb', exampleJp: '本を借りる。', exampleEn: '"I borrow a book."' },
  { word: '経験', reading: 'けいけん', meaning: 'experience', type: 'noun', exampleJp: 'いい経験になった。', exampleEn: '"It became a good experience."' },
  { word: '集める', reading: 'あつめる', meaning: 'to collect; to gather', type: 'ichidan-verb', exampleJp: '切手を集める。', exampleEn: '"I collect stamps."' },
  { word: '複雑', reading: 'ふくざつ', meaning: 'complicated; complex', type: 'na-adjective', exampleJp: 'この地図は複雑だ。', exampleEn: '"This map is complicated."' },
  { word: '届く', reading: 'とどく', meaning: 'to arrive; to reach', type: 'godan-verb', exampleJp: '手紙が届く。', exampleEn: '"The letter arrives."' },
  { word: '練習', reading: 'れんしゅう', meaning: 'practice', type: 'noun', exampleJp: '毎日練習する。', exampleEn: '"I practice every day."' },
  { word: '眠い', reading: 'ねむい', meaning: 'sleepy', type: 'i-adjective', exampleJp: 'とても眠い。', exampleEn: '"I am very sleepy."' },
  { word: '伝える', reading: 'つたえる', meaning: 'to convey; to tell', type: 'ichidan-verb', exampleJp: '気持ちを伝える。', exampleEn: '"I convey my feelings."' },
  { word: '丁寧', reading: 'ていねい', meaning: 'polite; careful', type: 'na-adjective', exampleJp: '丁寧に説明する。', exampleEn: '"I explain politely."' },
  { word: '探す', reading: 'さがす', meaning: 'to search; to look for', type: 'godan-verb', exampleJp: '鍵を探す。', exampleEn: '"I look for the key."' },
  { word: '景色', reading: 'けしき', meaning: 'scenery; view', type: 'noun', exampleJp: '景色がきれいだ。', exampleEn: '"The scenery is beautiful."' },
  { word: '壊れる', reading: 'こわれる', meaning: 'to break (intransitive)', type: 'ichidan-verb', exampleJp: '時計が壊れる。', exampleEn: '"The clock breaks."' },
  { word: '残念', reading: 'ざんねん', meaning: 'regrettable; unfortunate', type: 'na-adjective', exampleJp: '残念な結果だった。', exampleEn: '"It was an unfortunate result."' },
  { word: '誘う', reading: 'さそう', meaning: 'to invite', type: 'godan-verb', exampleJp: '友達を誘う。', exampleEn: '"I invite a friend."' },
  { word: '約束', reading: 'やくそく', meaning: 'promise; appointment', type: 'noun', exampleJp: '約束を守る。', exampleEn: '"I keep the promise."' },
  { word: '優しい', reading: 'やさしい', meaning: 'kind; gentle', type: 'i-adjective', exampleJp: '彼は優しい人だ。', exampleEn: '"He is a kind person."' },
  { word: '受ける', reading: 'うける', meaning: 'to receive; to take (exam)', type: 'ichidan-verb', exampleJp: '試験を受ける。', exampleEn: '"I take an exam."' },
  { word: '自由', reading: 'じゆう', meaning: 'freedom; free', type: 'na-adjective', exampleJp: '自由な時間が欲しい。', exampleEn: '"I want free time."' },
  { word: '捨てる', reading: 'すてる', meaning: 'to throw away', type: 'ichidan-verb', exampleJp: 'ゴミを捨てる。', exampleEn: '"I throw away the trash."' },
  // New words
  { word: '泳ぐ', reading: 'およぐ', meaning: 'to swim', type: 'godan-verb', exampleJp: '海で泳ぐ。', exampleEn: '"I swim in the sea."' },
  { word: '運ぶ', reading: 'はこぶ', meaning: 'to carry', type: 'godan-verb', exampleJp: '荷物を運ぶ。', exampleEn: '"I carry the luggage."' },
  { word: '起きる', reading: 'おきる', meaning: 'to wake up; to get up', type: 'ichidan-verb', exampleJp: '早く起きる。', exampleEn: '"I wake up early."' },
  { word: '落ちる', reading: 'おちる', meaning: 'to fall', type: 'ichidan-verb', exampleJp: '葉が落ちる。', exampleEn: '"The leaves fall."' },
  { word: '変える', reading: 'かえる', meaning: 'to change', type: 'ichidan-verb', exampleJp: '計画を変える。', exampleEn: '"I change the plan."' },
  { word: '考える', reading: 'かんがえる', meaning: 'to think; to consider', type: 'ichidan-verb', exampleJp: '答えを考える。', exampleEn: '"I think of the answer."' },
  { word: '決める', reading: 'きめる', meaning: 'to decide', type: 'ichidan-verb', exampleJp: '目標を決める。', exampleEn: '"I decide on a goal."' },
  { word: '聞こえる', reading: 'きこえる', meaning: 'to be audible; to hear', type: 'ichidan-verb', exampleJp: '音楽が聞こえる。', exampleEn: '"I can hear the music."' },
  { word: '比べる', reading: 'くらべる', meaning: 'to compare', type: 'ichidan-verb', exampleJp: '値段を比べる。', exampleEn: '"I compare the prices."' },
  { word: '困る', reading: 'こまる', meaning: 'to be troubled; to be in a fix', type: 'godan-verb', exampleJp: '道に迷って困る。', exampleEn: '"I am troubled after getting lost."' },
  { word: '転ぶ', reading: 'ころぶ', meaning: 'to fall down; to tumble', type: 'godan-verb', exampleJp: '滑って転ぶ。', exampleEn: '"I slip and fall down."' },
  { word: '触る', reading: 'さわる', meaning: 'to touch', type: 'godan-verb', exampleJp: '猫に触る。', exampleEn: '"I touch the cat."' },
  { word: '調べる', reading: 'しらべる', meaning: 'to investigate; to look up', type: 'ichidan-verb', exampleJp: '言葉を調べる。', exampleEn: '"I look up the word."' },
  { word: '信じる', reading: 'しんじる', meaning: 'to believe', type: 'ichidan-verb', exampleJp: '友達を信じる。', exampleEn: '"I believe my friend."' },
  { word: '育てる', reading: 'そだてる', meaning: 'to raise; to bring up', type: 'ichidan-verb', exampleJp: '子供を育てる。', exampleEn: '"I raise a child."' },
  { word: '続ける', reading: 'つづける', meaning: 'to continue', type: 'ichidan-verb', exampleJp: '練習を続ける。', exampleEn: '"I continue practicing."' },
  { word: '手伝う', reading: 'てつだう', meaning: 'to help; to assist', type: 'godan-verb', exampleJp: '母を手伝う。', exampleEn: '"I help my mother."' },
  { word: '直す', reading: 'なおす', meaning: 'to fix; to correct', type: 'godan-verb', exampleJp: '時計を直す。', exampleEn: '"I fix the clock."' },
  { word: '並ぶ', reading: 'ならぶ', meaning: 'to line up; to stand in a row', type: 'godan-verb', exampleJp: '列に並ぶ。', exampleEn: '"I line up in the queue."' },
  { word: '逃げる', reading: 'にげる', meaning: 'to run away; to escape', type: 'ichidan-verb', exampleJp: '危険から逃げる。', exampleEn: '"I escape from danger."' },
  { word: '脱ぐ', reading: 'ぬぐ', meaning: 'to take off (clothes)', type: 'godan-verb', exampleJp: '靴を脱ぐ。', exampleEn: '"I take off my shoes."' },
  { word: '登る', reading: 'のぼる', meaning: 'to climb', type: 'godan-verb', exampleJp: '山に登る。', exampleEn: '"I climb the mountain."' },
  { word: '払う', reading: 'はらう', meaning: 'to pay', type: 'godan-verb', exampleJp: '料金を払う。', exampleEn: '"I pay the fee."' },
  { word: '減る', reading: 'へる', meaning: 'to decrease; to diminish', type: 'godan-verb', exampleJp: '体重が減る。', exampleEn: '"My weight decreases."' },
  { word: '曲がる', reading: 'まがる', meaning: 'to turn; to bend', type: 'godan-verb', exampleJp: '角を曲がる。', exampleEn: '"I turn the corner."' },
  { word: '守る', reading: 'まもる', meaning: 'to protect; to keep (a promise)', type: 'godan-verb', exampleJp: 'ルールを守る。', exampleEn: '"I follow the rules."' },
  { word: '見える', reading: 'みえる', meaning: 'to be visible; can see', type: 'ichidan-verb', exampleJp: '海が見える。', exampleEn: '"I can see the sea."' },
  { word: '向かう', reading: 'むかう', meaning: 'to head toward; to face', type: 'godan-verb', exampleJp: '駅に向かう。', exampleEn: '"I head toward the station."' },
  { word: '戻る', reading: 'もどる', meaning: 'to return; to go back', type: 'godan-verb', exampleJp: '家に戻る。', exampleEn: '"I return home."' },
  { word: '焼く', reading: 'やく', meaning: 'to bake; to grill', type: 'godan-verb', exampleJp: 'パンを焼く。', exampleEn: '"I bake bread."' },
  { word: '意見', reading: 'いけん', meaning: 'opinion', type: 'noun', exampleJp: '意見を言う。', exampleEn: '"I state my opinion."' },
  { word: '機会', reading: 'きかい', meaning: 'opportunity; chance', type: 'noun', exampleJp: '機会を活かす。', exampleEn: '"I make use of the opportunity."' },
  { word: '記念', reading: 'きねん', meaning: 'commemoration; memory', type: 'noun', exampleJp: '記念写真を撮る。', exampleEn: '"I take a commemorative photo."' },
  { word: '計画', reading: 'けいかく', meaning: 'plan', type: 'noun', exampleJp: '計画を立てる。', exampleEn: '"I make a plan."' },
  { word: '原因', reading: 'げんいん', meaning: 'cause; reason', type: 'noun', exampleJp: '事故の原因を調べる。', exampleEn: '"I investigate the cause of the accident."' },
  { word: '事故', reading: 'じこ', meaning: 'accident', type: 'noun', exampleJp: '交通事故が起きた。', exampleEn: '"A traffic accident occurred."' },
  { word: '準備', reading: 'じゅんび', meaning: 'preparation', type: 'noun', exampleJp: '準備ができた。', exampleEn: '"The preparations are done."' },
  { word: '場所', reading: 'ばしょ', meaning: 'place; location', type: 'noun', exampleJp: '待ち合わせの場所を決める。', exampleEn: '"I decide on a meeting place."' },
  { word: '心配', reading: 'しんぱい', meaning: 'worry; concern', type: 'noun', exampleJp: '心配をかけてごめん。', exampleEn: '"Sorry for causing worry."' },
  { word: '生活', reading: 'せいかつ', meaning: 'daily life; living', type: 'noun', exampleJp: '生活が豊かになった。', exampleEn: '"My life became rich."' },
  { word: '説明', reading: 'せつめい', meaning: 'explanation', type: 'noun', exampleJp: '説明を聞く。', exampleEn: '"I listen to the explanation."' },
  { word: '相談', reading: 'そうだん', meaning: 'consultation; discussion', type: 'noun', exampleJp: '先生に相談する。', exampleEn: '"I consult with the teacher."' },
  { word: '注意', reading: 'ちゅうい', meaning: 'caution; attention', type: 'noun', exampleJp: '注意して運転する。', exampleEn: '"I drive carefully."' },
  { word: '日常', reading: 'にちじょう', meaning: 'everyday; daily life', type: 'noun', exampleJp: '日常の生活を大切にする。', exampleEn: '"I value everyday life."' },
  { word: '費用', reading: 'ひよう', meaning: 'cost; expense', type: 'noun', exampleJp: '費用を計算する。', exampleEn: '"I calculate the cost."' },
  { word: '文化', reading: 'ぶんか', meaning: 'culture', type: 'noun', exampleJp: '日本の文化を学ぶ。', exampleEn: '"I learn about Japanese culture."' },
  { word: '方法', reading: 'ほうほう', meaning: 'method; way', type: 'noun', exampleJp: '勉強の方法を変える。', exampleEn: '"I change my study method."' },
  { word: '理由', reading: 'りゆう', meaning: 'reason', type: 'noun', exampleJp: '理由を説明する。', exampleEn: '"I explain the reason."' },
  { word: '旅行', reading: 'りょこう', meaning: 'travel; trip', type: 'noun', exampleJp: '旅行の計画を立てる。', exampleEn: '"I make travel plans."' },
  { word: '明るい', reading: 'あかるい', meaning: 'bright; cheerful', type: 'i-adjective', exampleJp: '部屋が明るい。', exampleEn: '"The room is bright."' },
  { word: '怪しい', reading: 'あやしい', meaning: 'suspicious; strange', type: 'i-adjective', exampleJp: '怪しい人がいる。', exampleEn: '"There is a suspicious person."' },
  { word: '忙しい', reading: 'いそがしい', meaning: 'busy', type: 'i-adjective', exampleJp: '毎日忙しい。', exampleEn: '"I am busy every day."' },
  { word: '嬉しい', reading: 'うれしい', meaning: 'happy; glad', type: 'i-adjective', exampleJp: '合格して嬉しい。', exampleEn: '"I am happy to have passed."' },
  { word: '悲しい', reading: 'かなしい', meaning: 'sad', type: 'i-adjective', exampleJp: '別れが悲しい。', exampleEn: '"The farewell is sad."' },
  { word: '難しい', reading: 'むずかしい', meaning: 'difficult', type: 'i-adjective', exampleJp: 'この問題は難しい。', exampleEn: '"This problem is difficult."' },
  { word: '珍しい', reading: 'めずらしい', meaning: 'rare; unusual', type: 'i-adjective', exampleJp: '珍しい鳥を見た。', exampleEn: '"I saw a rare bird."' },
  { word: '厳しい', reading: 'きびしい', meaning: 'strict; severe', type: 'i-adjective', exampleJp: '先生が厳しい。', exampleEn: '"The teacher is strict."' },
  { word: '悔しい', reading: 'くやしい', meaning: 'frustrated; vexed', type: 'i-adjective', exampleJp: '負けて悔しい。', exampleEn: '"I feel frustrated after losing."' },
  { word: '正しい', reading: 'ただしい', meaning: 'correct; right', type: 'i-adjective', exampleJp: '正しい答えを選ぶ。', exampleEn: '"I choose the correct answer."' },
  { word: '便利', reading: 'べんり', meaning: 'convenient', type: 'na-adjective', exampleJp: 'スマホは便利だ。', exampleEn: '"Smartphones are convenient."' },
  { word: '不便', reading: 'ふべん', meaning: 'inconvenient', type: 'na-adjective', exampleJp: '田舎は不便だ。', exampleEn: '"The countryside is inconvenient."' },
  { word: '正確', reading: 'せいかく', meaning: 'accurate; precise', type: 'na-adjective', exampleJp: '正確な情報が必要だ。', exampleEn: '"Accurate information is needed."' },
  { word: '大切', reading: 'たいせつ', meaning: 'important; precious', type: 'na-adjective', exampleJp: '時間を大切にする。', exampleEn: '"I value my time."' },
  { word: '必要', reading: 'ひつよう', meaning: 'necessary', type: 'na-adjective', exampleJp: '努力が必要だ。', exampleEn: '"Effort is necessary."' },
  { word: '豊か', reading: 'ゆたか', meaning: 'rich; abundant', type: 'na-adjective', exampleJp: '自然が豊かな国だ。', exampleEn: '"It is a country rich in nature."' },
  { word: '適切', reading: 'てきせつ', meaning: 'appropriate; suitable', type: 'na-adjective', exampleJp: '適切な言葉を選ぶ。', exampleEn: '"I choose appropriate words."' },
  { word: '十分', reading: 'じゅうぶん', meaning: 'sufficient; enough', type: 'na-adjective', exampleJp: '準備は十分だ。', exampleEn: '"The preparation is sufficient."' },
  { word: '真剣', reading: 'しんけん', meaning: 'serious; earnest', type: 'na-adjective', exampleJp: '真剣に考える。', exampleEn: '"I think seriously."' },
  { word: '安全', reading: 'あんぜん', meaning: 'safe; secure', type: 'na-adjective', exampleJp: 'この道は安全だ。', exampleEn: '"This road is safe."' },
  { word: '特別', reading: 'とくべつ', meaning: 'special', type: 'na-adjective', exampleJp: '今日は特別な日だ。', exampleEn: '"Today is a special day."' },
];

// Word dictionary: word -> [reading, meaning]
const W = {
  '走る':   ['はしる',   'to run'],
  '話す':   ['はなす',   'to speak'],
  '始める': ['はじめる', 'to begin'],
  '忘れる': ['わすれる', 'to forget'],
  '選ぶ':   ['えらぶ',   'to choose'],
  '集める': ['あつめる', 'to collect'],
  '届く':   ['とどく',   'to reach; to arrive'],
  '伝える': ['つたえる', 'to convey; to tell'],
  '借りる': ['かりる',   'to borrow'],
  '探す':   ['さがす',   'to search for'],
  '壊れる': ['こわれる', 'to break; to be broken'],
  '誘う':   ['さそう',   'to invite'],
  '受ける': ['うける',   'to receive; to take'],
  '捨てる': ['すてる',   'to throw away'],
  '泳ぐ':   ['およぐ',   'to swim'],
  '運ぶ':   ['はこぶ',   'to carry; to transport'],
  '起きる': ['おきる',   'to wake up; to occur'],
  '落ちる': ['おちる',   'to fall; to drop'],
  '変える': ['かえる',   'to change'],
  '考える': ['かんがえる','to think; to consider'],
  '決める': ['きめる',   'to decide'],
  '困る':   ['こまる',   'to be troubled'],
  '調べる': ['しらべる', 'to investigate; to look up'],
  '信じる': ['しんじる', 'to believe'],
  '続ける': ['つづける', 'to continue'],
  '手伝う': ['てつだう', 'to help; to assist'],
  '直す':   ['なおす',   'to fix; to correct'],
  '並ぶ':   ['ならぶ',   'to line up'],
  '逃げる': ['にげる',   'to run away; to escape'],
  '脱ぐ':   ['ぬぐ',     'to take off (clothes)'],
  '登る':   ['のぼる',   'to climb'],
  '払う':   ['はらう',   'to pay'],
  '減る':   ['へる',     'to decrease'],
  '曲がる': ['まがる',   'to turn; to bend'],
  '守る':   ['まもる',   'to protect; to keep'],
  '見える': ['みえる',   'to be visible; to appear'],
  '向かう': ['むかう',   'to head towards'],
  '戻る':   ['もどる',   'to return'],
  '焼く':   ['やく',     'to grill; to bake'],
  '触る':   ['さわる',   'to touch'],
  '静か':   ['しずか',   'quiet; calm'],
  '暖かい': ['あたたかい','warm'],
  '危ない': ['あぶない', 'dangerous'],
  '眠い':   ['ねむい',   'sleepy'],
  '丁寧':   ['ていねい', 'polite; careful'],
  '複雑':   ['ふくざつ', 'complicated'],
  '残念':   ['ざんねん', 'unfortunate; regrettable'],
  '優しい': ['やさしい', 'kind; gentle'],
  '自由':   ['じゆう',   'freedom; free'],
  '明るい': ['あかるい', 'bright; cheerful'],
  '忙しい': ['いそがしい','busy'],
  '嬉しい': ['うれしい', 'happy; glad'],
  '悲しい': ['かなしい', 'sad'],
  '難しい': ['むずかしい','difficult'],
  '正しい': ['ただしい', 'correct; right'],
  '便利':   ['べんり',   'convenient'],
  '大切':   ['たいせつ', 'important; precious'],
  '必要':   ['ひつよう', 'necessary'],
  '安全':   ['あんぜん', 'safe; safety'],
  '特別':   ['とくべつ', 'special'],
  '珍しい': ['めずらしい','rare; unusual'],
  '厳しい': ['きびしい', 'strict; harsh'],
  '悔しい': ['くやしい', 'frustrating; vexing'],
  '怪しい': ['あやしい', 'suspicious; shady'],
  '豊か':   ['ゆたか',   'abundant; rich'],
  '適切':   ['てきせつ', 'appropriate; suitable'],
  '十分':   ['じゅうぶん','enough; sufficient'],
  '真剣':   ['しんけん', 'serious; earnest'],
  '正確':   ['せいかく', 'accurate; precise'],
  '不便':   ['ふべん',   'inconvenient'],
  '天気':   ['てんき',   'weather'],
  '経験':   ['けいけん', 'experience'],
  '練習':   ['れんしゅう','practice'],
  '景色':   ['けしき',   'scenery; view'],
  '約束':   ['やくそく', 'promise'],
  '意見':   ['いけん',   'opinion'],
  '計画':   ['けいかく', 'plan'],
  '準備':   ['じゅんび', 'preparation'],
  '心配':   ['しんぱい', 'worry; concern'],
  '問題':   ['もんだい', 'problem; question'],
  '機会':   ['きかい',   'opportunity; chance'],
  '記念':   ['きねん',   'commemoration; memory'],
  '原因':   ['げんいん', 'cause; origin'],
  '事故':   ['じこ',     'accident'],
  '場所':   ['ばしょ',   'place; location'],
  '生活':   ['せいかつ', 'daily life; living'],
  '説明':   ['せつめい', 'explanation'],
  '相談':   ['そうだん', 'consultation; discussion'],
  '注意':   ['ちゅうい', 'caution; attention'],
  '費用':   ['ひよう',   'cost; expense'],
  '文化':   ['ぶんか',   'culture'],
  '方法':   ['ほうほう', 'method; way'],
  '理由':   ['りゆう',   'reason'],
  '旅行':   ['りょこう', 'travel; trip'],
  '日常':   ['にちじょう','everyday; daily routine'],
};

// dr(word, knew) — drill entry
function dr(word, knew) {
  return { word, reading: W[word][0], meaning: W[word][1], knew };
}

// wr(word) — word-only entry (for added/cleared)
function wr(word) {
  return { word, reading: W[word][0], meaning: W[word][1] };
}

const activityData = {
  // ── Week of Mar 23 (current week) ──────────────────────────────────────────
  '2026-03-23': {
    drilled: [
      dr('旅行', true), dr('景色', true), dr('経験', false),
      dr('文化', true), dr('記念', false),
    ],
    added: [],
    cleared: [],
  },

  // ── Week of Mar 16 ─────────────────────────────────────────────────────────
  '2026-03-16': {
    drilled: [
      dr('走る', true), dr('話す', true), dr('始める', false),
      dr('忘れる', true), dr('選ぶ', true), dr('集める', false),
      dr('届く', true), dr('伝える', true),
    ],
    added: [wr('旅行'), wr('景色'), wr('経験'), wr('文化'), wr('記念')],
    cleared: [],
  },
  '2026-03-17': {
    drilled: [
      dr('借りる', true), dr('探す', false), dr('壊れる', false),
      dr('誘う', true), dr('受ける', true), dr('捨てる', true),
      dr('泳ぐ', true), dr('運ぶ', false), dr('起きる', true),
      dr('落ちる', true),
    ],
    added: [],
    cleared: [],
  },
  '2026-03-18': {
    drilled: [
      dr('変える', true), dr('考える', true), dr('決める', false),
      dr('困る', true), dr('調べる', true), dr('信じる', true),
      dr('続ける', false),
    ],
    added: [wr('相談'), wr('説明')],
    cleared: [],
  },
  '2026-03-19': {
    drilled: [
      dr('手伝う', true), dr('直す', true), dr('並ぶ', true),
      dr('逃げる', false), dr('脱ぐ', true), dr('登る', true),
      dr('払う', true), dr('減る', false), dr('曲がる', true),
      dr('守る', true),
    ],
    added: [],
    cleared: [wr('走る'), wr('話す'), wr('選ぶ')],
  },
  // Mar 20 (Fri) — rest day, no entry
  '2026-03-21': {
    drilled: [
      dr('見える', true), dr('向かう', false), dr('戻る', true),
      dr('焼く', true), dr('触る', true), dr('静か', true),
    ],
    added: [],
    cleared: [],
  },
  // Mar 22 (Sun) — rest day, no entry

  // ── Week of Mar 9 ──────────────────────────────────────────────────────────
  '2026-03-09': {
    drilled: [
      dr('暖かい', true), dr('危ない', false), dr('眠い', true),
      dr('丁寧', true), dr('複雑', false), dr('残念', true),
      dr('優しい', true), dr('自由', true),
    ],
    added: [wr('見える'), wr('向かう'), wr('戻る'), wr('焼く'), wr('触る')],
    cleared: [],
  },
  '2026-03-10': {
    drilled: [
      dr('明るい', true), dr('忙しい', true), dr('嬉しい', false),
      dr('悲しい', true), dr('難しい', false), dr('正しい', true),
      dr('便利', true), dr('大切', true), dr('必要', false),
      dr('安全', true),
    ],
    added: [],
    cleared: [],
  },
  '2026-03-11': {
    drilled: [
      dr('特別', true), dr('珍しい', false), dr('厳しい', true),
      dr('悔しい', true), dr('怪しい', false), dr('豊か', true),
      dr('適切', true), dr('十分', true),
    ],
    added: [wr('天気'), wr('練習'), wr('準備')],
    cleared: [wr('借りる'), wr('泳ぐ')],
  },
  // Mar 12 (Thu) — rest day
  '2026-03-13': {
    drilled: [
      dr('真剣', true), dr('正確', false), dr('不便', true),
      dr('天気', true), dr('経験', true), dr('練習', true),
      dr('約束', false), dr('意見', true), dr('計画', true),
      dr('準備', true),
    ],
    added: [],
    cleared: [],
  },
  '2026-03-14': {
    drilled: [
      dr('心配', false), dr('問題', true), dr('機会', true),
      dr('記念', true), dr('原因', false), dr('事故', true),
    ],
    added: [wr('約束'), wr('意見'), wr('計画')],
    cleared: [],
  },
  // Mar 15 (Sun) — rest day

  // ── Week of Mar 2 ──────────────────────────────────────────────────────────
  '2026-03-02': {
    drilled: [
      dr('場所', true), dr('生活', true), dr('説明', false),
      dr('相談', true), dr('注意', true), dr('費用', false),
      dr('文化', true), dr('方法', true),
    ],
    added: [wr('場所'), wr('生活'), wr('注意'), wr('費用'), wr('方法')],
    cleared: [],
  },
  '2026-03-03': {
    drilled: [
      dr('理由', true), dr('日常', true), dr('景色', false),
      dr('旅行', true), dr('経験', true), dr('文化', true),
      dr('記念', false), dr('問題', true), dr('原因', true),
      dr('事故', false),
    ],
    added: [],
    cleared: [],
  },
  '2026-03-04': {
    drilled: [
      dr('走る', true), dr('忘れる', true), dr('集める', false),
      dr('届く', true), dr('壊れる', true), dr('受ける', false),
      dr('捨てる', true), dr('運ぶ', true),
    ],
    added: [wr('理由'), wr('日常')],
    cleared: [wr('届く'), wr('運ぶ'), wr('受ける')],
  },
  // Mar 5 (Thu) — rest day
  '2026-03-06': {
    drilled: [
      dr('考える', true), dr('決める', true), dr('信じる', false),
      dr('続ける', true), dr('逃げる', true), dr('払う', false),
      dr('守る', true), dr('静か', true),
    ],
    added: [],
    cleared: [],
  },
  '2026-03-07': {
    drilled: [
      dr('暖かい', true), dr('丁寧', true), dr('優しい', false),
      dr('自由', true), dr('明るい', true), dr('忙しい', false),
      dr('難しい', true), dr('大切', true), dr('必要', true),
      dr('安全', false),
    ],
    added: [],
    cleared: [wr('考える'), wr('続ける'), wr('守る')],
  },
  // Mar 8 (Sun) — rest day

  // ── Week of Feb 23 (Feb 23 – Mar 1) ────────────────────────────────────────
  '2026-02-23': {
    drilled: [
      dr('話す', true), dr('始める', false), dr('選ぶ', true),
      dr('伝える', true), dr('借りる', false), dr('探す', true),
      dr('誘う', true), dr('起きる', true),
    ],
    added: [wr('暖かい'), wr('危ない'), wr('眠い'), wr('丁寧'), wr('複雑'), wr('残念')],
    cleared: [],
  },
  '2026-02-24': {
    drilled: [
      dr('落ちる', true), dr('変える', false), dr('困る', true),
      dr('調べる', true), dr('手伝う', true), dr('直す', false),
      dr('並ぶ', true), dr('脱ぐ', true),
    ],
    added: [],
    cleared: [],
  },
  '2026-02-25': {
    drilled: [
      dr('登る', true), dr('減る', false), dr('曲がる', true),
      dr('見える', true), dr('焼く', true), dr('触る', false),
      dr('複雑', true), dr('残念', true), dr('優しい', true),
      dr('豊か', false),
    ],
    added: [wr('場所'), wr('生活'), wr('説明'), wr('相談')],
    cleared: [wr('話す'), wr('伝える'), wr('誘う')],
  },
  // Feb 26 (Thu) — rest day
  '2026-02-27': {
    drilled: [
      dr('特別', true), dr('珍しい', true), dr('厳しい', false),
      dr('悔しい', true), dr('怪しい', true), dr('真剣', false),
      dr('正確', true), dr('不便', true),
    ],
    added: [],
    cleared: [],
  },
  '2026-02-28': {
    drilled: [
      dr('天気', true), dr('練習', false), dr('景色', true),
      dr('約束', true), dr('意見', false), dr('計画', true),
      dr('準備', true), dr('心配', true), dr('問題', false),
      dr('機会', true),
    ],
    added: [wr('走る'), wr('話す'), wr('始める'), wr('忘れる'), wr('選ぶ'), wr('集める')],
    cleared: [],
  },
  '2026-03-01': {
    drilled: [
      dr('注意', true), dr('費用', true), dr('方法', false),
      dr('理由', true), dr('日常', true), dr('安全', true),
      dr('便利', false), dr('正しい', true),
    ],
    added: [],
    cleared: [wr('特別'), wr('真剣'), wr('正確')],
  },

  // ── February 2026 (early) ─────────────────────────────────────────────────
  '2026-02-02': {
    drilled: [dr('考える',true), dr('決める',true), dr('困る',false), dr('続ける',true), dr('払う',true), dr('守る',false), dr('向かう',true)],
    added: [], cleared: [],
  },
  '2026-02-04': {
    drilled: [dr('逃げる',true), dr('直す',false), dr('見える',true), dr('戻る',true), dr('焼く',false), dr('静か',true), dr('豊か',true)],
    added: [], cleared: [],
  },
  '2026-02-06': {
    drilled: [dr('難しい',true), dr('必要',true), dr('大切',false), dr('安全',true), dr('自由',true), dr('明るい',false), dr('忙しい',true)],
    added: [], cleared: [],
  },
  '2026-02-09': {
    drilled: [dr('特別',true), dr('珍しい',false), dr('厳しい',true), dr('真剣',true), dr('正確',false), dr('不便',true), dr('悔しい',true)],
    added: [], cleared: [wr('考える'), wr('決める'), wr('守る')],
  },
  '2026-02-11': {
    drilled: [dr('天気',true), dr('経験',false), dr('練習',true), dr('準備',true), dr('心配',false), dr('問題',true), dr('機会',true)],
    added: [], cleared: [],
  },
  '2026-02-13': {
    drilled: [dr('記念',true), dr('原因',false), dr('事故',true), dr('景色',true), dr('旅行',false), dr('文化',true), dr('説明',true)],
    added: [], cleared: [],
  },
  '2026-02-16': {
    drilled: [dr('相談',true), dr('日常',false), dr('理由',true), dr('困る',true), dr('続ける',true), dr('払う',false), dr('便利',true)],
    added: [], cleared: [],
  },
  '2026-02-18': {
    drilled: [dr('信じる',true), dr('調べる',false), dr('手伝う',true), dr('並ぶ',true), dr('逃げる',false), dr('脱ぐ',true), dr('登る',true)],
    added: [], cleared: [wr('信じる'), wr('練習'), wr('準備')],
  },
  '2026-02-20': {
    drilled: [dr('減る',true), dr('曲がる',false), dr('見える',true), dr('戻る',true), dr('焼く',true), dr('触る',false), dr('静か',true), dr('豊か',true)],
    added: [], cleared: [],
  },

  // ── January 2026 ──────────────────────────────────────────────────────────
  '2026-01-02': {
    drilled: [dr('考える',true), dr('決める',false), dr('困る',true), dr('直す',true), dr('守る',true), dr('景色',false), dr('旅行',true)],
    added: [], cleared: [],
  },
  '2026-01-05': {
    drilled: [dr('逃げる',true), dr('払う',true), dr('続ける',false), dr('信じる',true), dr('調べる',true), dr('日常',false), dr('理由',true)],
    added: [], cleared: [],
  },
  '2026-01-07': {
    drilled: [dr('手伝う',true), dr('並ぶ',false), dr('脱ぐ',true), dr('登る',true), dr('減る',false), dr('曲がる',true), dr('豊か',true)],
    added: [], cleared: [wr('難しい'), wr('大切'), wr('安全')],
  },
  '2026-01-09': {
    drilled: [dr('見える',true), dr('向かう',true), dr('戻る',false), dr('焼く',true), dr('触る',true), dr('静か',false), dr('自由',true), dr('明るい',true)],
    added: [], cleared: [],
  },
  '2026-01-12': {
    drilled: [dr('忙しい',true), dr('必要',false), dr('便利',true), dr('正しい',true), dr('特別',false), dr('珍しい',true), dr('厳しい',true)],
    added: [], cleared: [],
  },
  '2026-01-14': {
    drilled: [dr('悔しい',true), dr('怪しい',false), dr('真剣',true), dr('正確',true), dr('不便',false), dr('天気',true), dr('経験',true)],
    added: [], cleared: [],
  },
  '2026-01-16': {
    drilled: [dr('練習',true), dr('準備',false), dr('心配',true), dr('問題',true), dr('機会',false), dr('記念',true), dr('原因',true)],
    added: [], cleared: [wr('明るい'), wr('忙しい'), wr('便利')],
  },
  '2026-01-19': {
    drilled: [dr('事故',true), dr('景色',false), dr('旅行',true), dr('文化',true), dr('説明',false), dr('相談',true), dr('日常',true)],
    added: [], cleared: [],
  },
  '2026-01-21': {
    drilled: [dr('理由',true), dr('考える',false), dr('決める',true), dr('困る',true), dr('直す',false), dr('守る',true), dr('向かう',true)],
    added: [], cleared: [],
  },
  '2026-01-23': {
    drilled: [dr('逃げる',true), dr('払う',false), dr('続ける',true), dr('信じる',true), dr('調べる',false), dr('手伝う',true), dr('並ぶ',true)],
    added: [], cleared: [wr('特別'), wr('怪しい'), wr('正確')],
  },
  '2026-01-26': {
    drilled: [dr('脱ぐ',true), dr('登る',true), dr('減る',false), dr('曲がる',true), dr('見える',true), dr('戻る',false), dr('焼く',true)],
    added: [], cleared: [],
  },
  '2026-01-28': {
    drilled: [dr('触る',true), dr('静か',true), dr('自由',false), dr('豊か',true), dr('天気',true), dr('練習',false), dr('準備',true), dr('問題',true)],
    added: [], cleared: [],
  },
  '2026-01-30': {
    drilled: [dr('心配',true), dr('機会',false), dr('記念',true), dr('原因',true), dr('事故',false), dr('説明',true), dr('相談',true)],
    added: [], cleared: [wr('正しい'), wr('不便')],
  },

  // ── December 2025 ─────────────────────────────────────────────────────────
  '2025-12-01': {
    drilled: [dr('困る',false), dr('逃げる',true), dr('払う',true), dr('続ける',true), dr('信じる',false), dr('見える',true), dr('向かう',true)],
    added: [wr('困る'), wr('逃げる'), wr('払う'), wr('続ける'), wr('信じる')],
    cleared: [],
  },
  '2025-12-03': {
    drilled: [dr('困る',true), dr('逃げる',true), dr('払う',false), dr('続ける',true), dr('信じる',true), dr('守る',true), dr('考える',false)],
    added: [], cleared: [],
  },
  '2025-12-05': {
    drilled: [dr('手伝う',true), dr('並ぶ',false), dr('脱ぐ',true), dr('登る',true), dr('減る',false), dr('曲がる',true)],
    added: [wr('手伝う'), wr('並ぶ'), wr('脱ぐ'), wr('登る'), wr('減る'), wr('曲がる')],
    cleared: [wr('静か'), wr('自由')],
  },
  '2025-12-08': {
    drilled: [dr('手伝う',true), dr('並ぶ',true), dr('脱ぐ',false), dr('登る',true), dr('困る',true), dr('逃げる',false), dr('払う',true)],
    added: [], cleared: [],
  },
  '2025-12-10': {
    drilled: [dr('豊か',true), dr('日常',false), dr('理由',true), dr('続ける',true), dr('信じる',true), dr('手伝う',true), dr('脱ぐ',false)],
    added: [wr('豊か'), wr('日常'), wr('理由')],
    cleared: [],
  },
  '2025-12-12': {
    drilled: [dr('豊か',true), dr('日常',true), dr('理由',false), dr('登る',true), dr('減る',true), dr('曲がる',false), dr('景色',true), dr('旅行',true)],
    added: [], cleared: [wr('難しい'), wr('大切')],
  },
  '2025-12-15': {
    drilled: [dr('逃げる',true), dr('払う',true), dr('続ける',true), dr('信じる',false), dr('文化',true), dr('説明',false), dr('相談',true), dr('豊か',true)],
    added: [], cleared: [],
  },
  '2025-12-17': {
    drilled: [dr('困る',true), dr('調べる',true), dr('手伝う',false), dr('並ぶ',true), dr('日常',true), dr('理由',true), dr('天気',true), dr('経験',false)],
    added: [wr('調べる')], cleared: [],
  },
  '2025-12-19': {
    drilled: [dr('脱ぐ',true), dr('登る',true), dr('減る',false), dr('曲がる',true), dr('特別',true), dr('真剣',true), dr('正確',false), dr('悔しい',true)],
    added: [], cleared: [wr('必要'), wr('便利')],
  },
  '2025-12-22': {
    drilled: [dr('豊か',true), dr('日常',true), dr('理由',true), dr('景色',false), dr('旅行',true), dr('文化',true), dr('練習',true), dr('問題',true)],
    added: [], cleared: [],
  },
  '2025-12-26': {
    drilled: [dr('心配',true), dr('機会',false), dr('記念',true), dr('原因',true), dr('説明',true), dr('相談',false), dr('珍しい',true), dr('厳しい',true)],
    added: [], cleared: [],
  },
  '2025-12-29': {
    drilled: [dr('逃げる',true), dr('払う',true), dr('続ける',false), dr('信じる',true), dr('調べる',true), dr('手伝う',true), dr('並ぶ',false), dr('豊か',true)],
    added: [], cleared: [wr('景色'), wr('旅行')],
  },

  // ── November 2025 ─────────────────────────────────────────────────────────
  '2025-11-03': {
    drilled: [dr('考える',true), dr('決める',false), dr('困る',true), dr('直す',true), dr('守る',false), dr('見える',true)],
    added: [wr('考える'), wr('決める'), wr('困る'), wr('直す'), wr('守る'), wr('見える'), wr('向かう'), wr('戻る')],
    cleared: [],
  },
  '2025-11-05': {
    drilled: [dr('考える',true), dr('決める',true), dr('困る',false), dr('直す',true), dr('守る',true), dr('見える',false), dr('向かう',true), dr('戻る',true)],
    added: [wr('焼く'), wr('触る'), wr('静か'), wr('自由'), wr('明るい'), wr('忙しい')],
    cleared: [],
  },
  '2025-11-07': {
    drilled: [dr('焼く',false), dr('触る',true), dr('静か',true), dr('自由',true), dr('明るい',false), dr('忙しい',true), dr('考える',true), dr('守る',true)],
    added: [wr('難しい'), wr('大切'), wr('必要'), wr('安全'), wr('便利'), wr('正しい')],
    cleared: [],
  },
  '2025-11-10': {
    drilled: [dr('難しい',true), dr('大切',false), dr('必要',true), dr('安全',true), dr('便利',false), dr('正しい',true), dr('静か',true), dr('自由',true)],
    added: [wr('特別'), wr('珍しい'), wr('厳しい')],
    cleared: [],
  },
  '2025-11-12': {
    drilled: [dr('特別',false), dr('珍しい',true), dr('厳しい',false), dr('難しい',true), dr('必要',true), dr('安全',true), dr('明るい',true)],
    added: [wr('悔しい'), wr('怪しい'), wr('真剣'), wr('正確')],
    cleared: [],
  },
  '2025-11-14': {
    drilled: [
      dr('悔しい',true), dr('怪しい',false), dr('真剣',true), dr('正確',true), dr('特別',true), dr('珍しい',true), dr('厳しい',true), dr('大切',true),
      dr('難しい',false), dr('必要',true), dr('安全',true), dr('便利',false), dr('正しい',true), dr('自由',true), dr('明るい',false), dr('忙しい',true),
      dr('静か',true), dr('豊か',false), dr('焼く',true), dr('触る',true), dr('見える',false), dr('向かう',true), dr('戻る',true), dr('焼く',false),
      dr('困る',true), dr('直す',false), dr('守る',true), dr('考える',true), dr('決める',false), dr('逃げる',true), dr('払う',true), dr('続ける',false),
      dr('信じる',true), dr('調べる',true), dr('手伝う',false), dr('並ぶ',true), dr('脱ぐ',false), dr('登る',true), dr('減る',true), dr('曲がる',false),
    ],
    added: [
      wr('不便'), wr('天気'), wr('経験'), wr('練習'), wr('準備'), wr('心配'), wr('問題'), wr('機会'),
      wr('記念'), wr('原因'), wr('事故'), wr('景色'), wr('旅行'), wr('文化'), wr('説明'), wr('相談'),
      wr('日常'), wr('理由'),
    ],
    cleared: [wr('静か'), wr('豊か'), wr('大切'), wr('必要'), wr('安全'), wr('便利')],
  },
  '2025-11-17': {
    drilled: [dr('不便',false), dr('天気',true), dr('経験',true), dr('練習',false), dr('真剣',true), dr('正確',true), dr('悔しい',true), dr('便利',true)],
    added: [], cleared: [],
  },
  '2025-11-19': {
    drilled: [dr('準備',true), dr('心配',false), dr('問題',true), dr('機会',true), dr('天気',true), dr('経験',true), dr('不便',true), dr('練習',true)],
    added: [wr('準備'), wr('心配'), wr('問題'), wr('機会')],
    cleared: [],
  },
  '2025-11-21': {
    drilled: [dr('記念',true), dr('原因',false), dr('事故',true), dr('準備',true), dr('問題',true), dr('機会',false), dr('正しい',true), dr('安全',true)],
    added: [wr('記念'), wr('原因'), wr('事故')],
    cleared: [wr('考える'), wr('決める')],
  },
  '2025-11-24': {
    drilled: [dr('景色',true), dr('旅行',false), dr('文化',true), dr('記念',true), dr('原因',true), dr('事故',false), dr('天気',true), dr('練習',true)],
    added: [wr('景色'), wr('旅行'), wr('文化')],
    cleared: [],
  },
  '2025-11-26': {
    drilled: [dr('景色',true), dr('旅行',true), dr('文化',true), dr('心配',true), dr('問題',false), dr('機会',true), dr('厳しい',true), dr('珍しい',true)],
    added: [], cleared: [],
  },
  '2025-11-28': {
    drilled: [dr('説明',true), dr('相談',false), dr('旅行',true), dr('文化',true), dr('記念',true), dr('経験',false), dr('練習',true), dr('必要',true)],
    added: [wr('説明'), wr('相談')],
    cleared: [wr('守る'), wr('見える'), wr('直す')],
  },
};

const stats = {
  lexiconSize:      96,
  activeWords:      72,
  clearedLifetime:  28,
  streakDays:        7,
  daysActiveMonth:  18,
  // progress bar segments
  drillsCleared:    84,   // words that reached their target
  drillsClose:      38,   // active, <= 4 drills remaining
  drillsMid:        57,   // active, <= 8 drills remaining
  drillsFar:        53,   // active, > 8 drills remaining
  drillsRemaining: 128,   // total drills still needed across all active words
};
